### ISSUE TITLE
Exception in filterworker <ArgumentError: wrong number of arguments (1 for 3)>

### ISSUE THREAD

**Issue by mahnunchik** [logstash-plugins/logstash-filter-multiline#10] opened 2015-03-17 12:29 UTC
```
filter {
  multiline {
    pattern => "^\s\s"
    what => "previous"
  }
}
```

```
Exception in filterworker {
  "exception"=>#<ArgumentError: wrong number of arguments (1 for 3)>, 
  "backtrace"=>[
    "/opt/logstash/lib/logstash/event.rb:286:in `to_hash_with_metadata'",      
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:271:in `merge'", 
    "org/jruby/RubyArray.java:1613:in `each'",
    "org/jruby/RubyEnumerable.java:865:in `inject'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:270:in `merge'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:204:in `flush'", 
    "org/jruby/RubyHash.java:1341:in `each'", 
    "org/jruby/RubyEnumerable.java:763:in `map'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:202:in `flush'", 
    "(eval):18:in `initialize'", 
    "org/jruby/RubyProc.java:271:in `call'",     
    "/opt/logstash/lib/logstash/pipeline.rb:289:in `flush_filters'", 
    "org/jruby/RubyArray.java:1613:in `each'", 
    "/opt/logstash/lib/logstash/pipeline.rb:288:in `flush_filters'", 
    "/opt/logstash/lib/logstash/pipeline.rb:297:in `flush_filters_to_output!'", 
    "/opt/logstash/lib/logstash/pipeline.rb:214:in `filterworker'", 
    "org/jruby/ext/thread/Mutex.java:149:in `synchronize'",
     "/opt/logstash/lib/logstash/pipeline.rb:214:in `filterworker'", 
    "/opt/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], 
  :level=>:error}
```

```bash
$ bin/logstash --version
logstash 1.5.0.rc2
```

**Comment by ramreddy26** [comment] 2015-04-15 20:40
I am having same issue.. are u able to fix it?

**Comment by ph** [comment] 2015-04-16 14:31
I've tried to reproduce this error with 1.5.0rc2 without success.
Would you mind sharing your configuration and/or date to reproduce it?
```
Logstash startup completed
New log event
  Add1
  Add2
{
       "message" => "New log event\n  Add1\n  Add2",
      "@version" => "1",
    "@timestamp" => "2015-04-16T14:29:05.404Z",
          "host" => "sashimi",
          "tags" => [
        [0] "multiline"
    ]
}``

Config: 

input { stdin {} }
filter {
  multiline {
    pattern => "^\s\s"
    what => "previous"
  }
}
output {
  stdout {
    codec => rubydebug
  }
}

**Comment by ramreddy26** [comment] 2015-04-16 14:34
Hi ..this is my config file https://gist.github.com/ramreddy26/f1c5350df746882f2f5c

**Comment by ph** [comment] 2015-04-16 15:07
@mahnunchik @ramreddy26 Are you both using courier as the input plugin?

**Comment by ramreddy26** [comment] 2015-04-16 15:11
@ph Yes I am using courier as input plugin

**Comment by mahnunchik** [comment] 2015-04-16 15:19
I am using `lumberjack` as input plugin.
But this bug was reproduced with `stdin` as input.

**Comment by ph** [comment] 2015-04-16 15:24
@mahnunchik do you have a simple test case to reproduce it?

**Comment by ramreddy26** [comment] 2015-04-16 15:30
Below is my shipper config file. When I run it using the filters in  indexer.conf file, the logs dont go through. I removed the filters and the logs are processed without any issues. Also I downgraded logstash 1.5.0 rc2 to 1.4.2 and now it seems to be working with the filters.
https://gist.github.com/ramreddy26/ee650d37b74c72df2bae

**Comment by ph** [comment] 2015-04-16 18:14
Seem related to our jrjackson integration.

Can reproduce with this.
```
{"message": "NO working" }

input { stdin { codec => json_lines } }
filter {
  grok {
     match => ["message", "%{WORD:[@metadata][method]}"]
  }
  multiline {
    pattern => "^\s\s"
    what => "previous"
  }
}
output {
  stdout {
    codec => rubydebug {
      metadata => true
    }
  }
}

**Comment by ph** [comment] 2015-04-16 18:17
pairing with @colinsurprenant to fix this.

**Comment by ph** [comment] 2015-04-16 19:14
Okay, this issue seem related to a change in

**Comment by ph** [comment] 2015-04-16 19:20
OK,  to reproduce this issue you need to convert the source from a JSON string to a hash (The hash is actually a java hashmap instance). This issue seem related to Java version, JDK 8 provides their own implementation of List#sort, Map#replace, and Map#merge (see https://github.com/jruby/jruby/issues/1249 for reference) and this is conflicting with our merge.

@ramreddy26 @mahnunchik Can you confirm the java version you are running? (using java -version)

The fix is actually to add a monkey patch in our `java_integration` in master to fix this issue, the fix will be included in RC3.

**Comment by ramreddy26** [comment] 2015-04-16 20:35
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by ph** [comment] 2015-04-16 21:01
Using this PR https://github.com/elastic/logstash/pull/3035 from `logstash-core` will fix this issue with JDK8.

Thank you for the report!

```
~/e/logstash git:fix/java8_merge ❯❯❯ bin/logstash -f ~/es/logstash-config/multiline.conf                                                                                                                                                                   ⏎ ✱
Logstash startup completed
{"message": "not working"}
{
       "message" => "not working",
      "@version" => "1",
    "@timestamp" => "2015-04-16T20:59:19.526Z",
          "host" => "sashimi",
     "@metadata" => {
        "method" => "not"
    }
}```

**Closed** 2015-04-17 12:43 UTC

**Comment by colinsurprenant** [comment] 2015-04-17 12:48
this fix will be live at either RC3 release or with realease 1.5.0.rc3.snapshot4  of [logstash-core](https://rubygems.org/gems/logstash-core/)
